export enum FeaturesActionType {
  FEATURES_IDLE = "FEATURES_IDLE",
  FEATURES_LOADING = "FEATURES_LOADING",
  FEATURES_LOADED = "FEATURES_LOADED",
  FEATURES_ERROR = "FEATURES_ERROR",
  SET_PAGINATION_INDEX = "SET_PAGINATION_INDEX",
  SET_PAGINATION_PAGE = "SET_PAGINATION_PAGE",
}

export enum FormsActionType {
  INCREMENT_FORM_INDEX = "INCREMENT_FORM_INDEX",
  DECREMENT_FORM_INDEX = "DECREMENT_FORM_INDEX",
  SET_CIRCULAR_FORM_LATITUDE = "SET_CIRCULAR_FORM_LATITUDE",
  SET_CIRCULAR_FORM_LONGITUDE = "SET_CIRCULAR_FORM_LONGITUDE",
  SET_CIRCULAR_FORM_RADIUS = "SET_CIRCULAR_FORM_RADIUS",
}
