export enum ActionType {
  SET_SHAPE_CIRCULAR = "SET_SHAPE_CIRCULAR",
  SET_SHAPE_RECTANGULAR = "SET_SHAPE_RECTANGULAR",
}

export enum FeaturesActionType {
  FEATURES_IDLE = "FEATURES_IDLE",
  FEATURES_LOADING = "FEATURES_LOADING",
  FEATURES_LOADED = "FEATURES_LOADED",
  FEATURES_ERROR = "FEATURES_ERROR",
  SET_PAGINATION_INDEX = "SET_PAGINATION_INDEX",
  SET_PAGINATION_PAGE = "SET_PAGINATION_PAGE",
}

export enum TabActionType {
  SET_TAB = "SET_TAB",
}
